stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: dilshodpirmatov/mydjangobackend:latest

build_and_push:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE
  only:
    - main  # Автоматизация только для ветки main