# Generated by Django 5.1.3 on 2025-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="cover_image",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genres",
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
