# Generated by Django 5.1.3 on 2025-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_cover_image_book_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, to="books.genre"),
        ),
    ]
